### ISSUE TITLE
Error: `data` must be uniquely named but has duplicate columns

### ISSUE THREAD

**Issue by ncchung** [thomasp85/particles#5] opened 2018-04-14 21:43 UTC
When I try to run examples presented in this README or its vignette, I get the following error.

> Error: `data` must be uniquely named but has duplicate columns

R version 3.3.3, with latest particles, ggraph, and so on.

**Comment by Atrebas** [comment] 2018-09-12 14:45
I've just encountered the same error in a different context.
May be related to [ggplot2](https://github.com/tidyverse/ggplot2/issues/2641) or [rlang](https://github.com/r-lib/rlang/issues/214).
This is due to duplicated colnames.

**Comment by jsan4christ** [comment] 2018-10-15 09:14
Dropping the duplicate column fixed this issue for me

**Comment by simonlee184** [comment] 2018-10-15 16:31
The issue isn't with the R version, but the ggplot2 version. install ggplot2 version 2.2.1 and it should work!
require(devtools)
install_version("ggplot2", version = "2.2.1", repos = "http://cran.us.r-project.org")

**Comment by dtsallos** [comment] 2018-11-13 08:39
Error persists. Is there an update on that? 

Using an older version is only a temporary solution which might be limiting in some ways.

**Comment by thomasp85** [comment] 2018-11-13 08:40
haven't had time to look into it, but @jsan4christ's solution is generally applicable...

**Comment by dtsallos** [comment] 2018-11-13 08:52
Well, I have only unique values on my data set and I want to compare the distribution of 2 classes of data (only using aes(x,y, fill= category) ) in geom_boxplot or geom_dotplot with code that works in version 2.2.1 as suggested by @simonlee184. Although, if I try using facets then it won't work. Maybe other issues arise when installing the older version. I need to look into those now too. 

In the newer version it tells me that there are duplicates when there aren't any. I checked it using all sorts of commands and removing any possible duplicate.

**Comment by thomasp85** [comment] 2018-11-13 08:54
It is difficult to help without a reproducible example. In general it is complaining about duplicate column names, not duplicate values

**Comment by dtsallos** [comment] 2018-11-13 09:14
A few things were corrupt in the process of trying to find out what was wrong. Got it all fixed now. Your suggestion to works, just renamed columns this time. Sorry for bothering.

**Comment by deepakag5** [comment] 2018-12-17 17:52
You can use below code  which should resolve the issue.
`colnames(data) <- make.unique(names(data))`

**Comment by canerferhatoglu** [comment] 2019-09-06 02:32
@iamdeepaka, belive me man, you`re the man! After four hours of struggle, I fixed the problem using your suggestions.

**Comment by lenabrandt** [comment] 2020-05-01 18:23
@iamdeepaka thank you so much! this solution saved me hours of search

**Comment by val23n** [comment] 2020-08-10 14:39
@iamdeepaka I tried your code suggestion, and I was wondering if you had any thoughts about how to approach this error:
```
> colnames(cds) <- make.unique(names(cds))
Error in make.unique(names(cds)) : 'names' must be a character vector
```
Since "cds" is a cell_data_set, I wonder if you have to approach making unique names a different way. Thanks in advance!

**Comment by 7117summer** [comment] 2020-11-29 23:57
> 
> 
> @iamdeepaka I tried your code suggestion, and I was wondering if you had any thoughts about how to approach this error:
> 
> ```
> > colnames(cds) <- make.unique(names(cds))
> Error in make.unique(names(cds)) : 'names' must be a character vector
> ```
> same question
> Since "cds" is a cell_data_set, I wonder if you have to approach making unique names a different way. Thanks in advance!

**Closed as completed** 2022-08-19 06:31 UTC
